### ISSUE TITLE
Raspberry PI2/OSMC Issues

### ISSUE THREAD

**Issue by sei4eto** [srg70/pvr.puzzle.tv#3]
Hello!
Thanks for the great PVR addon. I use it on MacOS without any problem. I use Shara.tv as a source. Everything works perfectly - live channels and archives. 

When I try to set up my PI3 with OSMC I've got several issues:
1) PVR.Puzzle - as only PVR client - the addon plays only live channels. When I try to play an archive - KODI freezes and I have to restart the media center. 
2) after uninstall/install the addon - no epg is loaded. I tried several epg sources - no success - https://www.ipstr.im/epg.xml.gz and the default epg for EDEM tv.
3) When I use two PVR (Puzzle + TVH) - both load but no channel group is loaded - all groups are shown as empty. The channels are visible only in All Channels group. And no EPG and archives are loaded from PVR.Puzzle addon. Only TVH loads EPG.
I tried to set priority in KODI's PVR settings for PVR clients - no change.

Please find two logs attched
[https://drive.google.com/open?id=1twfGHxF3fBbZq3Rf0pVAjqvOlF5OCQOI](url)
[https://drive.google.com/open?id=1jCXxSLfY9q9Hx8XLCjKrtpAEEdLbHSwQ](url)

Could you please advise if this related to OSMC or to PVR.Puzzle?
How can I fix it?
Thanks!
Keep yourself safe!

**Comment by srg70** [comment]
Hi,
First of all thanks for detailed description of a problem, and for the logs.
Unfortunately there are not too much to do with the issues. I believe, the main reason is a small amount of memory available on PI3 device. You have too many stuffs installed, and it will be hard to have all of them to work together.

1. I do not know whether one of the logs belong this issue, but probably, your live channels are not in HLS format, that requires more memory for processing.
2. I didn't found particular reason, but I see a failure during EPG cache loading. I believe it is also related to lack of free memory. Uninstalling of plugging does not removes temporary files, including EPG cache. You may try to remove the cache manually (or with "Reload EPG" item of context menu), and hopefully the first loading will succeed. But it will fail somewhen next time, when EPG cache will grow.
3. Both EPG and group issues are related to different channel IDs, provided by  PVRs to Kodi. PVR feature been developed for satellite channels, where channel IDs are same for different PVRs. With IPTV every add-on provides it's own channel ID. So the mixing of channels confuses Kodi with groups. So  Puzzle TV PVR can't provide EPG for TVH channel etc. You may try to group channels manually, through Kodi's interface. Try do disable usage of server groups in PVR settings of Kodi.

Unfortunately PVR interface is almost undocumented. Therefore I can't provide some links or so. All written above is my thoughts and filling :). But hopefully will help somehow.

All the best!

**Comment by sei4eto** [comment]
Thanks for your reply.
As I said I tried using two PVR (TVH and Puzzle) on OsX and Android TV - everything works flawlessly - including channel groups - they are shown correctly (from both TVH and Puzzle).
If I use only PVR.Puzzle on PI2 - it works as it is expected to work, but when I turn on the second PVR - no channel groups :(
So, I could speculate that issue is either in OSMC/KODI build or PVR.PUZZLE.addon for Pi2
I will try different OS for PI2 - AlexELEC, OpenElec and will see if it would work or not ( On libreELEC - cannot install PVR.Puzzle.addon - the ELEC doesn't open the repository)

**Comment by srg70** [comment]
Yah, I remember that I read somewhere about differences between Kodi and OSMC. Probably that is the reason.
If you failed to install repo on some system, you may try to install the add-on from ZIP file. Following is a link for Leia plugins https://github.com/srg70/kodi_leia/tree/master/repo

**Comment by sei4eto** [comment]
Hello again! :)
After some time spent trying different setups this is what I observed:
1. I turned off every other addons on my RPI2 system (OSMC) - I got enough free RAM (around 300-400 MB)
2. Managed to make my own groups using channel manager in KODI
3. When I start watching a channels - RAM usage increases - if I switch channels - the RAM consumes further. If I star playing an archive - the RAM consumption increases even faster.
And eventually RPI 2 freezes and I have to hard reset.
4. If I stop playing the channel - no RAM is cleared. 
5. If I use EPG from https://iptvx.one/epg/epg.xml.gz - it takes a lot of RAM (I suppose this is a huge EPG file). If I use default edem epg - it takes not much RAM as ishara epg does.

So after using the addon for some time the whole system crashes. 
Could this be a bug?
How can I fix this RAM consuming issue?
I use IPstream.one playlist with Shara TV plugin. TVH and Puzzle PVR addon
Thank you!
Log:
[https://drive.google.com/open?id=1WjtCzyLQ2sKBb7IasZbab7xPc3HL5RSz](url)

**Comment by srg70** [comment]
Hi and thanks again for log and description. I released new version 0.9.75 with lot of memory leaks fixed. In general, there are no major leaks, but on system with low amount of RAM it may be significant.

Please note:
1. "Fat" EPG consumes significantly more memory twice: EPG and Archive
2. Timeshift requires additional amount of memory, File o None mode is recommended
3. HLS streams, either archive or live requires additional 60-70 Mbytes for smooth playback. There is no control.for this setting.

Try a new build. Hopefully it will help.

**Comment by sei4eto** [comment]
Thanks a lot for the new build!
It works flawlessly on RPI 2 with OSMC.
I will test it for few days to see if memory leak will appear again.
Thank you again!

And one question more.
I know that PVR.Puzzle addon cannot combine two providers. But is there an option to install puzzle addon twice (as PVR.Puzzle2 for example) . Could you make a duplicate for your addon but with different name , so everyone who needs a second provider could install it as second addon?

**Comment by srg70** [comment]
Cool! Your feedback drew my attention on memory leaks check, and made possible this new version, thanks.

Regarding to make a copy... The main feature of this add-on is to combine several sources of streams under one interface, like it is done in the another great add-on Puzzle TV Server, just for PVR. Unfortunately it is not implemented yet, but must be done. So, you have to duplicate add-on manually, until the feature will be implemented.

**Comment by sei4eto** [comment]
> Cool! Your feedback drew my attention on memory leaks check, and made possible this new version, thanks.
> 
> Regarding to make a copy... The main feature of this add-on is to combine several sources of streams under one interface, like it is done in the another great add-on Puzzle TV Server, just for PVR. Unfortunately it is not implemented yet, but must be done. So, you have to duplicate add-on manually, until the feature will be implemented.

If you could point to guide how to duplicate the add-on ,would be much appreciated.
Thanks!

**Comment by srg70** [comment]
Well, it is out of scope of the issue. My impression was that you did it already. Honestly, I don't know exactly, but you may download version ZIP, unpack, change the ID of plugin, pack and try to install. In case of failure, probably a new build will require, and you have to build it for your platform (that is not trivial). Maybe it is better to stay with switch between providers for now.
