### ISSUE TITLE
Not working with coreelec s905x3

### ISSUE THREAD

**Issue by vilsonas** [srg70/pvr.puzzle.tv#4]
Hello i have issue its not working with s905x3 coreelec , i think its architecture problem. s905x3 use armv8 cpu maybe can fix this problem? Thank you

**Comment by srg70** [comment]
Hi, I have neither s905x3 hardware, no  armv8 build environment. But as far as I know armv8 may run armv7, or even aarch64 code. You may find in Kodi's log what is Kodi's architecture, and use the same fo the plugin.

**Comment by vilsonas** [comment]
s905x3 coreelec use aarch64 code, so i need install Linux arm 64bit? I try install all your version but got same error then i click turn on.

I tried use your plugin with s912 and works great.

**Comment by srg70** [comment]
Yes, if s905x3 coreelec uses aarch64 code, so you need to install Linux arm 64bit. I have to see Kodi's log file with error. Maybe it will help.

**Comment by vilsonas** [comment]
2020-04-10 14:45:07.117 T:4066398224  NOTICE: Starting Kodi (18.6 Git:ccf761beaceb2ec6d1e97227bb7d69b8ba2690b1). Platform: Linux ARM 32-bit
2020-04-10 14:45:07.117 T:4066398224  NOTICE: Using Release Kodi x32 build
2020-04-10 14:45:07.117 T:4066398224  NOTICE: Kodi compiled 2020-04-09 by GCC 8.3.0 for Linux ARM 32-bit version 4.9.113 (264561)
2020-04-10 14:45:07.117 T:4066398224  NOTICE: Running on CoreELEC (official): nightly_20200408 (9.2), kernel: Linux ARM 64-bit version 4.9.113 aarch64
2020-04-10 14:45:07.117 T:4066398224  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-04-10 14:45:07.117 T:4066398224  NOTICE: Host CPU: Amlogic S905X3 rev c, 4 cores available
2020-04-10 14:45:07.117 T:4066398224  NOTICE: ARM Features: Neon enabled


ERROR: Unable to load /storage/.kodi/addons/pvr.puzzle.tv/pvr.puzzle.tv.so.0.9.74, reason: /storage/.kodi/addons/pvr.puzzle.tv/pvr.puzzle.tv.so.0.9.74: wrong ELF class: ELFCLASS64ERROR: 
ERROR: UpdateAddons: Failed to create add-on PVR Puzzle TV, status = 5

**Comment by srg70** [comment]
Platform: Linux ARM 32-bit. You should use armV7 repo. Note, sometimes when you switch the repo, Kodi is still installing an old add-on version from download cache.

**Comment by vilsonas** [comment]
Like i said i try all version but still  not working its problem with addon.
I deleted old version before install , armv7 repo not working , arm 64 bit  also.
I got same error of both

**Comment by srg70** [comment]
Like I said before, if you have same error for different architects, Kodi installs same copy from the cache. You should clean it before new installation.

**Comment by srg70** [comment]
If you have a problem to find the cache folder on your device, read this https://beebom.com/clear-cache-on-kodi/
Disclaimer: I never use it personally.

**Comment by vilsonas** [comment]
I deleted cache with SSH  and now starts work , thanks!  But now new problem sometimes freeze puzzle about 1min and nothing i can do.

**Comment by srg70** [comment]
I can do nothing with this information. Provide description and debug log.
